#!/usr/bin/env python3
"""Generate data/languages/s390x_gaps.sinc — the 51 complete-set gap mnemonics.

Covers (all opcodes/formats verified against SA22-7832-14, 15th edition):
  RR   : MVCL(0E), CLCL(0F) [64 even-pair-unrolled real constructors each],
         LPR(10), LNR(11), LTR(12),
         LCR(13), ALR(1E), SLR(1F)
  RRE  : LPGR(B900), LNGR(B901), LTGR(B902), LCGR(B903), ALGR(B90A),
         SLGR(B90B), LPGFR(B910), LNGFR(B911), LCGFR(B913), AGFR(B918)
  RXa  : CVD(4E), CVB(4F) [16 R1-unrolled real constructors each], AL(5E), SL(5F)
  RXs  : STE(70)    (short-FPR store; RXs from s390x_fp.sinc)
  RXl  : STD(60)    (long-FPR store; RXl from s390x_fp.sinc)
  RIa  : IIHH(A5/0), NILH(A5/6), NILL(A5/7), OILL(A5/B)
  RILa : IIHF(C0/8), IILF(C0/9), NIHF(C0/A), OILF(C0/D)
  RILb : STRL(C4/F)
  RXYa : LTG(E3/02), ALG(E3/0A), SLG(E3/0B), LT(E3/12), AGF(E3/18),
         SGF(E3/19), ALGF(E3/1A), SLGF(E3/1B), CGF(E3/30), CLGF(E3/31),
         LTGF(E3/32), LGF(E3/14), LLGF(E3/16), LLGC(E3/90), LLGH(E3/91)
  RSb  : CLM(BD)    [16 mask-unrolled constructors]
  RSYb : CLMY(EB/21)[16 mask-unrolled constructors]
  RSYa : STMY(EB/90)[256 (R1,R3)-unrolled constructors]

Unrolling rationale (same as tools/gen_lmstm.py): SLEIGH has no dynamic
register indexing, so register-range (STMY) and mask-selected-byte (CLM/CLMY)
semantics are emitted as explicit constructors with straight-line pcode.

MVCL/CLCL/CVD/CVB are real p-code (interruptible completion approximated as
run-to-completion; exception cases documented as TODO in each constructor).
MVCL/CLCL unroll the 8x8 even-register pairs; CVD/CVB unroll R1 (16).

Output: data/languages/s390x_gaps.sinc (whole file).
Idempotent: re-running overwrites the file.
"""

import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

OUT = os.path.join(REPO_ROOT, "data/languages/s390x_gaps.sinc")

HEADER = """\
# =============================================================================
# s390x_gaps.sinc — complete-set gap fillers (51 mnemonics).
#
# Generated by tools/gen_gaps.py — do not hand-edit. Re-run the generator to
# change; hand-written sections live as Python strings in the generator.
#
# All opcodes, formats, and semantics verified against IBM z/Architecture
# Principles of Operation SA22-7832-14 (15th edition, April 2025). See the
# generator header for the opcode/format list.
#
# Inclusion: @included AFTER s390x_decimal.sinc in s390x.slaspec. Reuses:
#   tokens RR/RRE/RXa/RXYa/RSb/RSYa/RSYb/RIa/RILa/RILb (core),
#   RXs/RXl (s390x_fp.sinc), macros ea_D12/ea_D20/rel_RI32 (core),
#   RILb_Target (s390x_branch.sinc), cc_set/cc_add64/cc_sub64/cc_scmp64/
#   cc_ucmp/cc_logic (s390x_arith.sinc), registers r0-r15, f0h-f15h,
#   f0-f15, zero, cc.
#
# Conventions (inherited from the core spec):
#   - IBM bit numbering in comments is MSB=0; SLEIGH fields are LSB=0.
#   - Token fields are zero-extended into pcode expressions.
#   - Size discipline: :1 = 1 byte, :8 = 8 bytes. Cross with zext()
#     explicitly; SLEIGH rejects mixed-size operators.
#   - 32-bit register results preserve the high 32 bits of R1, matching the
#     existing arithmetic constructors.
#   - SLEIGH's `<` is signed; unsigned 64-bit compares use the sign-flip
#     trick (x ^ 0x8000000000000000) which maps unsigned order to signed.
# =============================================================================

"""

# ---------------------------------------------------------------------------
# Logical add/subtract CC helpers (not in s390x_arith.sinc, which only has
# signed add/sub and zero/nonzero logic helpers).
# PoP: ADD LOGICAL CC — 0=zero,no carry; 1=nonzero,no carry; 2=zero,carry;
# 3=nonzero,carry. SUBTRACT LOGICAL uses the identical encoding with
# carry = NOT borrow = (first >= second) unsigned.
# ---------------------------------------------------------------------------

CC_HELPERS = """\
# ---------------------------------------------------------------------------
# ADD/SUBTRACT LOGICAL condition-code helpers (PoP 7-28, 7-455).
# ---------------------------------------------------------------------------

# ADD LOGICAL, 32-bit: r/a are :8 holding masked 32-bit values (bit63=0,
# so signed `<` == unsigned `<`). Carry = wraparound = (r < a) unsigned.
macro cc_addlog32(r, a) {
    local ncc:1;
    ncc = 0;
    if (r >= a) goto <ccal32_nc>;
    ncc = 2;
<ccal32_nc>
    if (r == 0) goto <ccal32_done>;
    ncc = ncc | 1;
<ccal32_done>
    cc_set(ncc);
}

# ADD LOGICAL, 64-bit: full 64-bit operands; unsigned compare via sign-flip.
macro cc_addlog64(r, a) {
    local ncc:1;
    local rs:8;
    local as:8;
    rs = r ^ 0x8000000000000000;
    as = a ^ 0x8000000000000000;
    ncc = 0;
    if (rs >= as) goto <ccal64_nc>;
    ncc = 2;
<ccal64_nc>
    if (r == 0) goto <ccal64_done>;
    ncc = ncc | 1;
<ccal64_done>
    cc_set(ncc);
}

# SUBTRACT LOGICAL, 32-bit: carry = no borrow = (a >= b) unsigned.
macro cc_sublog32(r, a, b) {
    local ncc:1;
    ncc = 0;
    if (a < b) goto <ccsl32_nz>;
    ncc = 2;
<ccsl32_nz>
    if (r == 0) goto <ccsl32_done>;
    ncc = ncc | 1;
<ccsl32_done>
    cc_set(ncc);
}

# SUBTRACT LOGICAL, 64-bit: carry = (a >= b) unsigned via sign-flip.
macro cc_sublog64(r, a, b) {
    local ncc:1;
    local as:8;
    local bs:8;
    as = a ^ 0x8000000000000000;
    bs = b ^ 0x8000000000000000;
    ncc = 0;
    if (as < bs) goto <ccsl64_nz>;
    ncc = 2;
<ccsl64_nz>
    if (r == 0) goto <ccsl64_done>;
    ncc = ncc | 1;
<ccsl64_done>
    cc_set(ncc);
}

# LOAD AND TEST CC for a signed value: 0=zero, 1=negative, 2=positive.
# v is :8; signbit is 31 or 63.
macro cc_lttest(v, signbit) {
    local ncc:1;
    ncc = 0;
    if (v == 0) goto <cclt_done>;
    ncc = 2;
    if (((v >> signbit) & 1) == 0) goto <cclt_done>;
    ncc = 1;
<cclt_done>
    cc_set(ncc);
}

"""

# ---------------------------------------------------------------------------
# Hand-written constructors (non-unrolled).
# ---------------------------------------------------------------------------

RR_SECTION = """\
# ===========================================================================
# RR format: LPR/LNR/LTR/LCR/ALR/SLR (opcodes verified: PoP LOAD
# POSITIVE/NEGATIVE, LOAD AND TEST, LOAD COMPLEMENT, ADD/SUBTRACT LOGICAL).
# 32-bit semantics: result in bits 32-63 (SLEIGH low 32), high 32 preserved.
# ===========================================================================

# LPR: LOAD POSITIVE (32). R1[32:63] = abs(R2[32:63]).
# Overflow iff R2[32:63]==0x80000000 (result unchanged 0x80000000, CC=3).
# CC: 0=zero, 2=positive, 3=overflow (PoP 7-308).
:LPR "LPR " RR_R1 "," RR_R2 is RR_OP=0x10 & RR_R1 & RR_R2
{
    local a:8;
    local r:8;
    local ov:1;
    local ncc:1;
    a = RR_R2 & 0xffffffff;
    ov = (a == 0x80000000);
    r = a;
    if ((a & 0x80000000) == 0) goto <lpr_done>;
    r = (0 - a) & 0xffffffff;
<lpr_done>
    RR_R1 = (RR_R1 & 0xffffffff00000000) | r;
    ncc = 2;
    if (r == 0) goto <lpr_cc>;
    if (ov == 0) goto <lpr_cc>;
    ncc = 3;
    goto <lpr_cc>;
<lpr_cc>
    # ncc=2 (positive) unless r==0 or overflow; fix zero case:
    if (r != 0) goto <lpr_set>;
    ncc = 0;
    if (ov == 0) goto <lpr_set>;
    ncc = 3;
<lpr_set>
    cc_set(ncc);
}

# LNR: LOAD NEGATIVE (32). R1[32:63] = -abs(R2[32:63]).
# CC: 0=zero, 1=negative (PoP 7-309). No overflow possible.
:LNR "LNR " RR_R1 "," RR_R2 is RR_OP=0x11 & RR_R1 & RR_R2
{
    local a:8;
    local r:8;
    a = RR_R2 & 0xffffffff;
    r = a;
    if ((a & 0x80000000) != 0) goto <lnr_done>;
    r = (0 - a) & 0xffffffff;
<lnr_done>
    RR_R1 = (RR_R1 & 0xffffffff00000000) | r;
    cc_lttest(r, 31);
}

# LTR: LOAD AND TEST (32). R1[32:63] = R2[32:63].
# CC: 0=zero, 1=negative, 2=positive (PoP 7-310).
:LTR "LTR " RR_R1 "," RR_R2 is RR_OP=0x12 & RR_R1 & RR_R2
{
    local a:8;
    a = RR_R2 & 0xffffffff;
    RR_R1 = (RR_R1 & 0xffffffff00000000) | a;
    cc_lttest(a, 31);
}

# LCR: LOAD COMPLEMENT (32). R1[32:63] = -R2[32:63] (two's complement).
# Overflow iff R2[32:63]==0x80000000 (result unchanged, CC=3).
# CC: 0=zero, 1=negative, 2=positive, 3=overflow (PoP 7-174).
:LCR "LCR " RR_R1 "," RR_R2 is RR_OP=0x13 & RR_R1 & RR_R2
{
    local a:8;
    local r:8;
    local ov:1;
    a = RR_R2 & 0xffffffff;
    ov = (a == 0x80000000);
    r = (0 - a) & 0xffffffff;
    RR_R1 = (RR_R1 & 0xffffffff00000000) | r;
    if (ov == 0) goto <lcr_nov>;
    cc_set(3);
    goto <lcr_done>;
<lcr_nov>
    cc_lttest(r, 31);
<lcr_done>
}

# ALR: ADD LOGICAL (32). R1[32:63] = R1[32:63] + R2[32:63] (unsigned).
# CC: 0=zero,no carry; 1=nonzero,no carry; 2=zero,carry; 3=nonzero,carry.
:ALR "ALR " RR_R1 "," RR_R2 is RR_OP=0x1E & RR_R1 & RR_R2
{
    local a:8;
    local b:8;
    local r:8;
    a = RR_R1 & 0xffffffff;
    b = RR_R2 & 0xffffffff;
    r = (a + b) & 0xffffffff;
    RR_R1 = (RR_R1 & 0xffffffff00000000) | r;
    cc_addlog32(r, a);
}

# SLR: SUBTRACT LOGICAL (32). R1[32:63] = R1[32:63] - R2[32:63] (unsigned).
# CC encoding identical to ADD LOGICAL, carry = NOT borrow.
:SLR "SLR " RR_R1 "," RR_R2 is RR_OP=0x1F & RR_R1 & RR_R2
{
    local a:8;
    local b:8;
    local r:8;
    a = RR_R1 & 0xffffffff;
    b = RR_R2 & 0xffffffff;
    r = (a - b) & 0xffffffff;
    RR_R1 = (RR_R1 & 0xffffffff00000000) | r;
    cc_sublog32(r, a, b);
}

# MVCL/CLCL are generated below (gen_mvcl/gen_clcl): 64 even-pair-unrolled
# real-pcode constructors each. See the generator functions for the PoP
# semantics (7-331/7-173).

"""

RRE_SECTION = """\
# ===========================================================================
# RRE format (opcodes verified: PoP LOAD POSITIVE/NEGATIVE, LOAD AND TEST,
# LOAD COMPLEMENT, ADD/SUBTRACT LOGICAL, ADD sections).
# ===========================================================================

# LPGR: LOAD POSITIVE (64). R1 = abs(R2). Overflow iff R2==0x8000000000000000.
# CC: 0=zero, 2=positive, 3=overflow.
:LPGR "LPGR " RRE_R1 "," RRE_R2 is RRE_OP=0xB900 & RRE_R1 & RRE_R2
{
    local a:8;
    local r:8;
    local ov:1;
    local ncc:1;
    a = RRE_R2;
    ov = (a == 0x8000000000000000);
    r = a;
    if ((a & 0x8000000000000000) == 0) goto <lpgr_done>;
    r = 0 - a;
<lpgr_done>
    RRE_R1 = r;
    ncc = 2;
    if (r != 0) goto <lpgr_nz>;
    ncc = 0;
<lpgr_nz>
    if (ov == 0) goto <lpgr_set>;
    ncc = 3;
<lpgr_set>
    cc_set(ncc);
}

# LNGR: LOAD NEGATIVE (64). R1 = -abs(R2). CC: 0=zero, 1=negative.
:LNGR "LNGR " RRE_R1 "," RRE_R2 is RRE_OP=0xB901 & RRE_R1 & RRE_R2
{
    local a:8;
    local r:8;
    a = RRE_R2;
    r = a;
    if ((a & 0x8000000000000000) != 0) goto <lngr_done>;
    r = 0 - a;
<lngr_done>
    RRE_R1 = r;
    cc_lttest(r, 63);
}

# LTGR: LOAD AND TEST (64). R1 = R2. CC: 0=zero, 1=negative, 2=positive.
:LTGR "LTGR " RRE_R1 "," RRE_R2 is RRE_OP=0xB902 & RRE_R1 & RRE_R2
{
    local a:8;
    a = RRE_R2;
    RRE_R1 = a;
    cc_lttest(a, 63);
}

# LCGR: LOAD COMPLEMENT (64). R1 = -R2. Overflow iff R2==min (CC=3).
# CC: 0=zero, 1=negative, 2=positive, 3=overflow.
:LCGR "LCGR " RRE_R1 "," RRE_R2 is RRE_OP=0xB903 & RRE_R1 & RRE_R2
{
    local a:8;
    local r:8;
    local ov:1;
    a = RRE_R2;
    ov = (a == 0x8000000000000000);
    r = 0 - a;
    RRE_R1 = r;
    if (ov == 0) goto <lcgr_nov>;
    cc_set(3);
    goto <lcgr_done>;
<lcgr_nov>
    cc_lttest(r, 63);
<lcgr_done>
}

# ALGR: ADD LOGICAL (64). R1 = R1 + R2 (unsigned). CC via cc_addlog64.
:ALGR "ALGR " RRE_R1 "," RRE_R2 is RRE_OP=0xB90A & RRE_R1 & RRE_R2
{
    local a:8;
    local b:8;
    local r:8;
    a = RRE_R1;
    b = RRE_R2;
    r = a + b;
    RRE_R1 = r;
    cc_addlog64(r, a);
}

# SLGR: SUBTRACT LOGICAL (64). R1 = R1 - R2 (unsigned). CC via cc_sublog64.
:SLGR "SLGR " RRE_R1 "," RRE_R2 is RRE_OP=0xB90B & RRE_R1 & RRE_R2
{
    local a:8;
    local b:8;
    local r:8;
    a = RRE_R1;
    b = RRE_R2;
    r = a - b;
    RRE_R1 = r;
    cc_sublog64(r, a, b);
}

# LPGFR: LOAD POSITIVE (64<-32). R1 = abs(sign_extend(R2[32:63])).
# The maximum negative 32-bit number is complemented WITHOUT overflow
# (result 2^31, CC=2). CC: 0=zero, 2=positive.
:LPGFR "LPGFR " RRE_R1 "," RRE_R2 is RRE_OP=0xB910 & RRE_R1 & RRE_R2
{
    local a32:8;
    local sa:8;
    local r:8;
    a32 = RRE_R2 & 0xffffffff;
    sa = a32;
    if ((a32 & 0x80000000) == 0) goto <lpgfr_pos>;
    sa = a32 | 0xffffffff00000000;
<lpgfr_pos>
    r = sa;
    if ((sa & 0x8000000000000000) == 0) goto <lpgfr_done>;
    r = 0 - sa;
<lpgfr_done>
    RRE_R1 = r;
    cc_lttest(r, 63);
}

# LNGFR: LOAD NEGATIVE (64<-32). R1 = -abs(sign_extend(R2[32:63])).
# CC: 0=zero, 1=negative. No overflow possible.
:LNGFR "LNGFR " RRE_R1 "," RRE_R2 is RRE_OP=0xB911 & RRE_R1 & RRE_R2
{
    local a32:8;
    local sa:8;
    local r:8;
    a32 = RRE_R2 & 0xffffffff;
    sa = a32;
    if ((a32 & 0x80000000) == 0) goto <lngfr_pos>;
    sa = a32 | 0xffffffff00000000;
<lngfr_pos>
    r = sa;
    if ((sa & 0x8000000000000000) != 0) goto <lngfr_done>;
    r = 0 - sa;
<lngfr_done>
    RRE_R1 = r;
    cc_lttest(r, 63);
}

# LCGFR: LOAD COMPLEMENT (64<-32). R1 = -sign_extend(R2[32:63]).
# Complementing -2^31 yields 2^31 with NO overflow. CC: 0/1/2.
:LCGFR "LCGFR " RRE_R1 "," RRE_R2 is RRE_OP=0xB913 & RRE_R1 & RRE_R2
{
    local a32:8;
    local sa:8;
    local r:8;
    a32 = RRE_R2 & 0xffffffff;
    sa = a32;
    if ((a32 & 0x80000000) == 0) goto <lcgfr_pos>;
    sa = a32 | 0xffffffff00000000;
<lcgfr_pos>
    r = 0 - sa;
    RRE_R1 = r;
    cc_lttest(r, 63);
}

# AGFR: ADD (64<-32). R1 = R1 + sign_extend(R2[32:63]) (signed).
# CC via cc_add64 (signed overflow possible).
:AGFR "AGFR " RRE_R1 "," RRE_R2 is RRE_OP=0xB918 & RRE_R1 & RRE_R2
{
    local a:8;
    local b32:8;
    local b:8;
    local r:8;
    a = RRE_R1;
    b32 = RRE_R2 & 0xffffffff;
    b = b32;
    if ((b32 & 0x80000000) == 0) goto <agfr_pos>;
    b = b32 | 0xffffffff00000000;
<agfr_pos>
    r = a + b;
    RRE_R1 = r;
    cc_add64(r, (a >> 63) & 1, (b >> 63) & 1);
}

"""

RX_SECTION = """\
# ===========================================================================
# RXa format: CVD/CVB (decode-only), AL/SL.
# RXs/RXs: STE/STD (FP stores; RXs/RXl tokens from s390x_fp.sinc).
# ===========================================================================

# CVD/CVB are generated below (gen_cvd/gen_cvb): 16 R1-unrolled real-pcode
# constructors each. See the generator functions for the PoP semantics
# (7-267/7-266).

# AL: ADD LOGICAL (32). R1[32:63] = R1[32:63] + *(32-bit mem) (unsigned).
:AL "AL " RXa_R1 "," RXa_D2 "(" RXa_X2 "," RXa_B2 ")" is RXa_OP=0x5E & RXa_R1 & RXa_X2 & RXa_B2 & RXa_D2
{
    local ea:8;
    local m32:4;
    local a:8;
    local b:8;
    local r:8;
    ea_D12(ea, RXa_B2, RXa_X2, RXa_D2);
    m32 = *:4 ea;
    a = RXa_R1 & 0xffffffff;
    b = zext(m32);
    r = (a + b) & 0xffffffff;
    RXa_R1 = (RXa_R1 & 0xffffffff00000000) | r;
    cc_addlog32(r, a);
}

# SL: SUBTRACT LOGICAL (32). R1[32:63] = R1[32:63] - *(32-bit mem).
:SL "SL " RXa_R1 "," RXa_D2 "(" RXa_X2 "," RXa_B2 ")" is RXa_OP=0x5F & RXa_R1 & RXa_X2 & RXa_B2 & RXa_D2
{
    local ea:8;
    local m32:4;
    local a:8;
    local b:8;
    local r:8;
    ea_D12(ea, RXa_B2, RXa_X2, RXa_D2);
    m32 = *:4 ea;
    a = RXa_R1 & 0xffffffff;
    b = zext(m32);
    r = (a - b) & 0xffffffff;
    RXa_R1 = (RXa_R1 & 0xffffffff00000000) | r;
    cc_sublog32(r, a, b);
}

# STE: STORE (short, 70). 32-bit short FP datum = HIGH half of FPR
# (fNh alias, PoP 9-8); stored unchanged. CC unchanged.
:STE "STE " RXs_R1 "," RXs_D2 "(" RXs_X2 "," RXs_B2 ")" is RXs_OP=0x70 & RXs_R1 & RXs_X2 & RXs_B2 & RXs_D2
{
    local ea:8;
    ea_D12(ea, RXs_B2, RXs_X2, RXs_D2);
    *:4 ea = RXs_R1;
}

# STD: STORE (long, 60). 64-bit FPR stored unchanged. CC unchanged.
:STD "STD " RXl_R1 "," RXl_D2 "(" RXl_X2 "," RXl_B2 ")" is RXl_OP=0x60 & RXl_R1 & RXl_X2 & RXl_B2 & RXl_D2
{
    local ea:8;
    ea_D12(ea, RXl_B2, RXl_X2, RXl_D2);
    *:8 ea = RXl_R1;
}

"""

RI_SECTION = """\
# ===========================================================================
# RIa format (A5): IIHH/NILH/NILL/OILL (OPCDs verified: PoP INSERT/AND/OR
# IMMEDIATE sections). RIa_I2 is a signed 16-bit field; mask to raw bits.
# NILH/NILL/OILF CC is set from ONLY the 16 bits ANDed/ORed (PoP notes).
# RILa format (C0): IIHF/IILF/NIHF/OILF. CC unchanged for INSERT IMMEDIATE
# (absent from PoP Appendix C); AND/OR IMMEDIATE CC from the 32 replaced bits.
# ===========================================================================

# IIHH: INSERT IMMEDIATE high-high (A5/0). Insert I2 into IBM bits 0-15
# (SLEIGH high 16). CC unchanged.
:IIHH "IIHH " RIa_R1 "," RIa_I2 is RIa_OP=0xA5 & RIa_R1 & RIa_OPCD=0x0 & RIa_I2
{
    local i2:8;
    i2 = RIa_I2 & 0xffff;
    RIa_R1 = (RIa_R1 & 0x0000ffffffffffff) | (i2 << 48);
}

# NILH: AND IMMEDIATE low-high (A5/6). AND I2 into IBM bits 32-47
# (SLEIGH bits 16-31). CC from the 16 ANDed bits: 0=zero, 1=not zero.
:NILH "NILH " RIa_R1 "," RIa_I2 is RIa_OP=0xA5 & RIa_R1 & RIa_OPCD=0x6 & RIa_I2
{
    local i2:8;
    local r:8;
    i2 = RIa_I2 & 0xffff;
    r = ((RIa_R1 >> 16) & 0xffff) & i2;
    RIa_R1 = (RIa_R1 & 0xffffffff0000ffff) | (r << 16);
    cc_logic(r);
}

# NILL: AND IMMEDIATE low-low (A5/7). AND I2 into IBM bits 48-63
# (SLEIGH low 16). CC from the 16 ANDed bits.
:NILL "NILL " RIa_R1 "," RIa_I2 is RIa_OP=0xA5 & RIa_R1 & RIa_OPCD=0x7 & RIa_I2
{
    local i2:8;
    local r:8;
    i2 = RIa_I2 & 0xffff;
    r = (RIa_R1 & 0xffff) & i2;
    RIa_R1 = (RIa_R1 & 0xffffffffffff0000) | r;
    cc_logic(r);
}

# OILL: OR IMMEDIATE low-low (A5/B). OR I2 into IBM bits 48-63
# (SLEIGH low 16). CC from the 16 ORed bits: 0=zero, 1=not zero.
:OILL "OILL " RIa_R1 "," RIa_I2 is RIa_OP=0xA5 & RIa_R1 & RIa_OPCD=0xB & RIa_I2
{
    local i2:8;
    local r:8;
    i2 = RIa_I2 & 0xffff;
    r = (RIa_R1 & 0xffff) | i2;
    RIa_R1 = (RIa_R1 & 0xffffffffffff0000) | r;
    cc_logic(r);
}

# IIHF: INSERT IMMEDIATE high-full (C0/8). Insert I2 into IBM bits 0-31
# (SLEIGH high 32). CC unchanged.
:IIHF "IIHF " RILa_R1 "," RILa_I2 is RILa_OP=0xC0 & RILa_R1 & RILa_OPCD=0x8 & RILa_I2
{
    local i2:8;
    i2 = RILa_I2 & 0xffffffff;
    RILa_R1 = (RILa_R1 & 0x00000000ffffffff) | (i2 << 32);
}

# IILF: INSERT IMMEDIATE low-full (C0/9). Insert I2 into IBM bits 32-63
# (SLEIGH low 32). CC unchanged.
:IILF "IILF " RILa_R1 "," RILa_I2 is RILa_OP=0xC0 & RILa_R1 & RILa_OPCD=0x9 & RILa_I2
{
    local i2:8;
    i2 = RILa_I2 & 0xffffffff;
    RILa_R1 = (RILa_R1 & 0xffffffff00000000) | i2;
}

# NIHF: AND IMMEDIATE high-full (C0/A). AND I2 into IBM bits 0-31
# (SLEIGH high 32). CC from the 32 ANDed bits.
:NIHF "NIHF " RILa_R1 "," RILa_I2 is RILa_OP=0xC0 & RILa_R1 & RILa_OPCD=0xA & RILa_I2
{
    local i2:8;
    local r:8;
    i2 = RILa_I2 & 0xffffffff;
    r = ((RILa_R1 >> 32) & 0xffffffff) & i2;
    RILa_R1 = (RILa_R1 & 0x00000000ffffffff) | (r << 32);
    cc_logic(r);
}

# OILF: OR IMMEDIATE low-full (C0/D). OR I2 into IBM bits 32-63
# (SLEIGH low 32). CC from the 32 ORed bits.
:OILF "OILF " RILa_R1 "," RILa_I2 is RILa_OP=0xC0 & RILa_R1 & RILa_OPCD=0xD & RILa_I2
{
    local i2:8;
    local r:8;
    i2 = RILa_I2 & 0xffffffff;
    r = (RILa_R1 & 0xffffffff) | i2;
    RILa_R1 = (RILa_R1 & 0xffffffff00000000) | r;
    cc_logic(r);
}

"""

RXY_SECTION = """\
# ===========================================================================
# RXYa format (E3): second bytes verified against PoP Figure B-3 and the
# chapter-7 section figures. Display follows the core convention (DL2 only;
# all corpus vectors have DH2=0).
# ===========================================================================

# LTG: LOAD AND TEST (64). R1 = *(64-bit mem). CC: 0/1/2 signed (PoP 7-310).
:LTG "LTG " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x02
{
    local ea:8;
    local a:8;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    a = *:8 ea;
    RXYa_R1 = a;
    cc_lttest(a, 63);
}

# ALG: ADD LOGICAL (64). R1 = R1 + *(64-bit mem) (unsigned).
:ALG "ALG " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x0A
{
    local ea:8;
    local a:8;
    local b:8;
    local r:8;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    b = *:8 ea;
    a = RXYa_R1;
    r = a + b;
    RXYa_R1 = r;
    cc_addlog64(r, a);
}

# SLG: SUBTRACT LOGICAL (64). R1 = R1 - *(64-bit mem) (unsigned).
:SLG "SLG " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x0B
{
    local ea:8;
    local a:8;
    local b:8;
    local r:8;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    b = *:8 ea;
    a = RXYa_R1;
    r = a - b;
    RXYa_R1 = r;
    cc_sublog64(r, a, b);
}

# LT: LOAD AND TEST (32). R1[32:63] = *(32-bit mem); high 32 preserved.
# CC: 0/1/2 from signed 32-bit value (PoP 7-310).
:LT "LT " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x12
{
    local ea:8;
    local m32:4;
    local a:8;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    m32 = *:4 ea;
    a = zext(m32);
    RXYa_R1 = (RXYa_R1 & 0xffffffff00000000) | a;
    cc_lttest(a, 31);
}

# AGF: ADD (64<-32). R1 = R1 + sign_extend(*(32-bit mem)) (signed).
:AGF "AGF " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x18
{
    local ea:8;
    local m32:4;
    local a:8;
    local b:8;
    local r:8;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    m32 = *:4 ea;
    b = zext(m32);
    if ((b & 0x80000000) == 0) goto <agf_pos>;
    b = b | 0xffffffff00000000;
<agf_pos>
    a = RXYa_R1;
    r = a + b;
    RXYa_R1 = r;
    cc_add64(r, (a >> 63) & 1, (b >> 63) & 1);
}

# SGF: SUBTRACT (64<-32). R1 = R1 - sign_extend(*(32-bit mem)) (signed).
:SGF "SGF " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x19
{
    local ea:8;
    local m32:4;
    local a:8;
    local b:8;
    local r:8;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    m32 = *:4 ea;
    b = zext(m32);
    if ((b & 0x80000000) == 0) goto <sgf_pos>;
    b = b | 0xffffffff00000000;
<sgf_pos>
    a = RXYa_R1;
    r = a - b;
    RXYa_R1 = r;
    cc_sub64(r, (a >> 63) & 1, (b >> 63) & 1);
}

# ALGF: ADD LOGICAL (64<-32). R1 = R1 + zero_extend(*(32-bit mem)).
:ALGF "ALGF " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x1A
{
    local ea:8;
    local m32:4;
    local a:8;
    local b:8;
    local r:8;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    m32 = *:4 ea;
    b = zext(m32);
    a = RXYa_R1;
    r = a + b;
    RXYa_R1 = r;
    cc_addlog64(r, a);
}

# SLGF: SUBTRACT LOGICAL (64<-32). R1 = R1 - zero_extend(*(32-bit mem)).
:SLGF "SLGF " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x1B
{
    local ea:8;
    local m32:4;
    local a:8;
    local b:8;
    local r:8;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    m32 = *:4 ea;
    b = zext(m32);
    a = RXYa_R1;
    r = a - b;
    RXYa_R1 = r;
    cc_sublog64(r, a, b);
}

# CGF: COMPARE (64<-32). Signed compare R1 vs sign_extend(*(32-bit mem)).
# CC: 0=equal, 1=first low, 2=first high.
:CGF "CGF " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x30
{
    local ea:8;
    local m32:4;
    local b:8;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    m32 = *:4 ea;
    b = zext(m32);
    if ((b & 0x80000000) == 0) goto <cgf_pos>;
    b = b | 0xffffffff00000000;
<cgf_pos>
    cc_scmp64(RXYa_R1, b);
}

# CLGF: COMPARE LOGICAL (64<-32). Unsigned R1 vs zero_extend(*(32-bit)).
:CLGF "CLGF " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x31
{
    local ea:8;
    local m32:4;
    local b:8;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    m32 = *:4 ea;
    b = zext(m32);
    cc_ucmp(RXYa_R1, b);
}

# LTGF: LOAD AND TEST (64<-32). R1 = sign_extend(*(32-bit mem)).
# CC: 0/1/2 from signed 64-bit result (PoP 7-310).
:LTGF "LTGF " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x32
{
    local ea:8;
    local m32:4;
    local b:8;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    m32 = *:4 ea;
    b = zext(m32);
    if ((b & 0x80000000) == 0) goto <ltgf_pos>;
    b = b | 0xffffffff00000000;
<ltgf_pos>
    RXYa_R1 = b;
    cc_lttest(b, 63);
}

# LGF: LOAD (64<-32). R1 = sign_extend(*(32-bit mem)). CC unchanged.
:LGF "LGF " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x14
{
    local ea:8;
    local m32:4;
    local b:8;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    m32 = *:4 ea;
    b = zext(m32);
    if ((b & 0x80000000) == 0) goto <lgf_pos>;
    b = b | 0xffffffff00000000;
<lgf_pos>
    RXYa_R1 = b;
}

# LLGF: LOAD LOGICAL (64<-32). R1 = zero_extend(*(32-bit mem)). CC unchanged.
:LLGF "LLGF " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x16
{
    local ea:8;
    local m32:4;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    m32 = *:4 ea;
    RXYa_R1 = zext(m32);
}

# LLGC: LOAD LOGICAL CHARACTER (E3/90). R1 = zero_extend(*(8-bit mem)).
# CC unchanged (PoP 7-318).
:LLGC "LLGC " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x90
{
    local ea:8;
    local m8:1;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    m8 = *:1 ea;
    RXYa_R1 = zext(m8);
}

# LLGH: LOAD LOGICAL HALFWORD (E3/91). R1 = zero_extend(*(16-bit mem)).
# CC unchanged.
:LLGH "LLGH " RXYa_R1 "," RXYa_DL2 "(" RXYa_X2 "," RXYa_B2 ")" is RXYa_OP=0xE3 & RXYa_R1 & RXYa_X2 & RXYa_B2 & RXYa_DL2 & RXYa_DH2 & RXYa_OP2=0x91
{
    local ea:8;
    local m16:2;
    ea_D20(ea, RXYa_B2, RXYa_X2, RXYa_DH2, RXYa_DL2);
    m16 = *:2 ea;
    RXYa_R1 = zext(m16);
}

"""

STRL_SECTION = """\
# ===========================================================================
# RILb: STRL (STORE RELATIVE LONG, C4/0F). 32-bit store to PC-relative
# address (PoP 7-450). Uses RILb_Target (from s390x_branch.sinc) so the
# display prints the absolute target like Capstone.
# ===========================================================================

:STRL "STRL " RILb_R1 "," RILb_Target is RILb_OP=0xC4 & RILb_R1 & RILb_OPCD=0xF & RILb_RI2 & RILb_Target
{
    local ea:8;
    local w:4;
    rel_RI32(ea, RILb_RI2);
    w = RILb_R1:4;
    *:4 ea = w;
}

"""


def clm_body(mask, is_rsy):
    """Pcode body lines for a CLM/CLMY mask (0..15).

    Mask bit i (0=MSB, value 8>>i) selects IBM byte 32+8*i .. 39+8*i of R1,
    i.e. SLEIGH bits (24-8*i)..(31-8*i). Selected bytes are compared
    left-to-right against a contiguous storage field at EA. CC via cc_ucmp
    on the big-endian-assembled values (unsigned compare == lexicographic).
    Mask 0: one byte at EA is accessed (for access exceptions); CC=0.
    """
    # SLEIGH right-shifts for each mask bit, MSB-first.
    shifts = []
    for i in range(4):
        if mask & (8 >> i):
            shifts.append(24 - 8 * i)
    token = "RSYb" if is_rsy else "RSb"
    if is_rsy:
        ea_line = f"    ea_D20(ea, {token}_B2, zero, {token}_DH2, {token}_DL2);"
    else:
        ea_line = f"    ea_D12(ea, {token}_B2, zero, {token}_D2);"
    lines = ["    local ea:8;"]
    if not shifts:
        lines.append("    local dummy:1;")
        lines.append(ea_line)
        lines.append("    dummy = *:1 ea;")
        lines.append("    cc_set(0);")
        return lines
    lines.append("    local cv1:8;")
    lines.append("    local cv2:8;")
    lines.append(ea_line)
    # v1: selected R1 bytes, big-endian.
    parts = []
    for j, sh in enumerate(shifts):
        pos = 8 * (len(shifts) - 1 - j)
        if sh == 0:
            expr = f"({token}_R1 & 0xff)"
        else:
            expr = f"(({token}_R1 >> {sh}) & 0xff)"
        if pos:
            parts.append(f"({expr} << {pos})")
        else:
            parts.append(expr)
    lines.append(f"    cv1 = {' | '.join(parts)};")
    # v2: selected memory bytes, big-endian.
    parts = []
    for j in range(len(shifts)):
        pos = 8 * (len(shifts) - 1 - j)
        expr = f"zext(*:1 (ea + {j}))" if j else "zext(*:1 ea)"
        if pos:
            parts.append(f"({expr} << {pos})")
        else:
            parts.append(expr)
    lines.append(f"    cv2 = {' | '.join(parts)};")
    lines.append("    cc_ucmp(cv1, cv2);")
    return lines


def gen_clm():
    out = []
    out.append("# ===========================================================================")
    out.append("# RSb/RSYb: CLM (BD) / CLMY (EB/21), unrolled by 4-bit mask.")
    out.append("# PoP 7-172: mask bit i (MSB-first) selects IBM R1 byte 32+8*i; the")
    out.append("# selected bytes form a contiguous field compared left-to-right against")
    out.append("# storage at EA. CC: 0=equal, 1=first low, 2=first high.")
    out.append("# ===========================================================================")
    out.append("")
    for name, token, op, op2, is_rsy in [("CLM", "RSb", 0xBD, None, False),
                                         ("CLMY", "RSYb", 0xEB, 0x21, True)]:
        for mask in range(16):
            body = clm_body(mask, is_rsy)
            cname = f"{name}_{mask}"
            # Constrained M3 must print as a literal (like gen_muldiv.py).
            m_lit = f'"{mask}"'
            if is_rsy:
                isc = (f"{token}_OP=0x{op:02X} & {token}_R1 & {token}_M3={mask} & "
                       f"{token}_B2 & {token}_DL2 & {token}_DH2 & {token}_OP2=0x{op2:02X}")
                disp = (f'"{name} " {token}_R1 "," {m_lit} "," '
                        f'{token}_DL2 "(" {token}_B2 ")"')
            else:
                isc = (f"{token}_OP=0x{op:02X} & {token}_R1 & {token}_M3={mask} & "
                       f"{token}_B2 & {token}_D2")
                disp = (f'"{name} " {token}_R1 "," {m_lit} "," '
                        f'{token}_D2 "(" {token}_B2 ")"')
            out.append(f":{cname} {disp} is {isc}")
            out.append("{")
            out.extend(body)
            out.append("}")
            out.append("")
    return "\n".join(out)


def reg_seq(r1, r3):
    seq, r = [], r1
    while True:
        seq.append(r)
        if r == r3:
            break
        r = (r + 1) % 16
    return seq


def gen_stmy():
    out = []
    out.append("# ===========================================================================")
    out.append("# RSYa: STMY (EB/90), unrolled by (R1,R3). PoP 7-451: bits 32-63")
    out.append("# (SLEIGH low 32) of R1..R3 (wrapping 15->0) stored as successive")
    out.append("# 4-byte fields at EA. CC unchanged.")
    out.append("# Display prints R1/R3 as plain numbers (like gen_lmstm.py);")
    out.append("# tests/sleigh_diff.py maps them back to r-names for 'stmy'.")
    out.append("# ===========================================================================")
    out.append("")
    n = 0
    for r1 in range(16):
        for r3 in range(16):
            seq = reg_seq(r1, r3)
            isc = (f"RSYa_OP=0xEB & RSYa_R1={r1} & RSYa_R3={r3} & RSYa_B2 & "
                   f"RSYa_DL2 & RSYa_DH2 & RSYa_OP2=0x90")
            # Constrained R1/R3 print as literals (like gen_lmstm.py).
            disp = (f'"STMY " "{r1}" "," "{r3}" "," RSYa_DL2 "(" RSYa_B2 ")"')
            out.append(f":STMY_{r1}_{r3} {disp} is {isc}")
            out.append("{")
            out.append("    local ea:8; local w:4;")
            out.append("    ea_D20(ea, RSYa_B2, zero, RSYa_DH2, RSYa_DL2);")
            for i, r in enumerate(seq):
                out.append(f"    w = r{r}:4; *:4 ea = w;")
                if i != len(seq) - 1:
                    out.append("    ea = ea + 4;")
            out.append("}")
            out.append("")
            n += 1
    return "\n".join(out), n


def gen_cvd():
    """CVD (4E), unrolled by R1: 16 real-pcode constructors.

    PoP 7-267: the signed 32-bit integer in the low half of R1 is converted
    to packed decimal (15 digits + sign) and stored as the 8-byte second
    operand. Overflow cannot occur. CC unchanged.
    Display prints the constrained R1 as a literal r-name (like STMY).
    """
    out = []
    out.append("# ===========================================================================")
    out.append("# RXa: CVD (4E), unrolled by R1. PoP 7-267: signed low 32 bits of R1 ->")
    out.append("# 8-byte packed decimal (15 digits + sign). CC unchanged.")
    out.append("# ===========================================================================")
    out.append("")
    n = 0
    for r1 in range(16):
        p = f"cvd_{r1}"
        isc = (f"RXa_OP=0x4E & RXa_R1={r1} & RXa_X2 & RXa_B2 & RXa_D2")
        disp = (f'"CVD r{r1}," RXa_D2 "(" RXa_X2 "," RXa_B2 ")"')
        out.append(f":CVD_{r1} {disp} is {isc}")
        out.append("{")
        out.append("    local ea:8;")
        out.append("    local rv:8; local v32:8; local mag:8;")
        out.append("    local neg:1; local sgn:1;")
        out.append("    local i:8; local t:8; local t8:8; local d1:1;")
        out.append("    ea_D12(ea, RXa_B2, RXa_X2, RXa_D2);")
        out.append(f"    rv = r{r1};")
        out.append("    v32 = rv & 0xffffffff;")
        out.append("    neg = (v32 >= 0x80000000);")
        out.append("    mag = v32;")
        out.append(f"    if (neg == 0) goto <{p}_go>;")
        out.append("    mag = (0 - mag) & 0xffffffff;")
        out.append(f"<{p}_go>")
        out.append("    sgn = 0xc | neg;")
        out.append("    t = mag; i = 0;")
        out.append(f"<{p}_s>")
        out.append(f"    if (i == 15) goto <{p}_end>;")
        out.append("    t8 = t - 10 * (t / 10);")
        out.append("    d1 = t8[0,8];")
        out.append("    dec_stdig(ea, 8, i, d1, sgn);")
        out.append("    t = t / 10;")
        out.append("    i = i + 1;")
        out.append(f"    goto <{p}_s>;")
        out.append(f"<{p}_end>")
        out.append("}")
        out.append("")
        n += 1
    return "\n".join(out), n


def gen_cvb():
    """CVB (4F), unrolled by R1: 16 real-pcode constructors.

    PoP 7-266: the 8-byte signed packed-decimal second operand is converted
    to a signed 32-bit integer stored in the low half of R1; the high 32
    bits of R1 are unchanged. CC unchanged. On decimal overflow the low 32
    bits are stored and a fixed-point-divide exception occurs (TODO: the
    exception is not modeled). Invalid digits/signs are a data exception
    (TODO: not checked).
    Display prints the constrained R1 as a literal r-name (like STMY).
    """
    out = []
    out.append("# ===========================================================================")
    out.append("# RXa: CVB (4F), unrolled by R1. PoP 7-266: 8-byte signed packed ->")
    out.append("# signed 32-bit in low half of R1 (high half unchanged). CC unchanged.")
    out.append("# TODO: decimal-overflow fixed-point-divide exception; data exception")
    out.append("# on invalid digits/signs.")
    out.append("# ===========================================================================")
    out.append("")
    n = 0
    for r1 in range(16):
        p = f"cvb_{r1}"
        isc = (f"RXa_OP=0x4F & RXa_R1={r1} & RXa_X2 & RXa_B2 & RXa_D2")
        disp = (f'"CVB r{r1}," RXa_D2 "(" RXa_X2 "," RXa_B2 ")"')
        out.append(f":CVB_{r1} {disp} is {isc}")
        out.append("{")
        out.append("    local ea:8;")
        out.append("    local mag:8; local v:8;")
        out.append("    local b:1; local s:1; local neg:1; local d:1;")
        out.append("    local k:8;")
        out.append("    ea_D12(ea, RXa_B2, RXa_X2, RXa_D2);")
        out.append("    mag = 0;")
        out.append("    k = 14;")
        out.append(f"<{p}_p>")
        out.append("    dec_digit(ea, 8, k, d);")
        out.append("    mag = mag * 10 + zext(d);")
        out.append(f"    if (k == 0) goto <{p}_sgn>;")
        out.append("    k = k - 1;")
        out.append(f"    goto <{p}_p>;")
        out.append(f"<{p}_sgn>")
        out.append("    b = *:1 (ea + 7);")
        out.append("    s = b & 0xf;")
        out.append("    neg = (s == 0xd) | (s == 0xb);")
        out.append(f"    if (neg == 0) goto <{p}_pos>;")
        out.append("    v = 0 - mag;")
        out.append(f"    goto <{p}_w>;")
        out.append(f"<{p}_pos>")
        out.append("    v = mag;")
        out.append(f"<{p}_w>")
        out.append(f"    r{r1} = (r{r1} & 0xffffffff00000000) | (v & 0xffffffff);")
        out.append("}")
        out.append("")
        n += 1
    return "\n".join(out), n


def gen_mvcl():
    """MVCL (0E), unrolled by even (R1,R2): 64 real-pcode constructors.

    PoP 7-331: R1/R2 must be even (else specification exception; odd values
    have no constructor). R1/R2 hold addresses; the low 24 bits of R1+1/R2+1
    hold lengths; bits 32-39 of R2+1 hold the pad byte. Bytes are moved
    left to right; if the second operand is shorter, the remainder of the
    first is filled with the pad byte. CC from initial lengths: 0 = equal,
    1 = first shorter, 2 = first longer. Destructive overlap (first-operand
    start inside the second operand) => no move, CC=3. On completion the
    addresses are incremented and the lengths decremented by the bytes moved.
    Interruptibility (partial completion) is approximated as run-to-completion.
    Display prints the constrained registers as literal r-names (like STMY).
    """
    out = []
    out.append("# ===========================================================================")
    out.append("# RR: MVCL (0E), unrolled by even (R1,R2). PoP 7-331. See gen_mvcl().")
    out.append("# ===========================================================================")
    out.append("")
    n = 0
    for r1 in (0, 2, 4, 6, 8, 10, 12, 14):
        for r2 in (0, 2, 4, 6, 8, 10, 12, 14):
            p = f"mvcl_{r1}_{r2}"
            a1, l1, a2, l2 = f"r{r1}", f"r{r1+1}", f"r{r2}", f"r{r2+1}"
            isc = f"RR_OP=0x0E & RR_R1={r1} & RR_R2={r2}"
            disp = f'"MVCL r{r1},r{r2}"'
            out.append(f":MVCL_{r1}_{r2} {disp} is {isc}")
            out.append("{")
            out.append("    local n1:8; local n2:8; local pad:1; local pt:8;")
            out.append("    local i:8; local b:1;")
            out.append(f"    n1 = {l1} & 0xffffff;")
            out.append(f"    n2 = {l2} & 0xffffff;")
            out.append(f"    pt = ({l2} >> 24) & 0xff;")
            out.append("    pad = pt[0,8];")
            out.append(f"    if (n1 != n2) goto <{p}_c1>;")
            out.append("    cc = 0;")
            out.append(f"    goto <{p}_ov>;")
            out.append(f"<{p}_c1>")
            out.append(f"    if (n1 >= n2) goto <{p}_c2>;")
            out.append("    cc = 1;")
            out.append(f"    goto <{p}_ov>;")
            out.append(f"<{p}_c2>")
            out.append("    cc = 2;")
            out.append(f"<{p}_ov>")
            out.append(f"    if ({a1} <= {a2}) goto <{p}_go>;")
            out.append(f"    if ({a1} >= ({a2} + n2)) goto <{p}_go>;")
            out.append("    cc = 3;")
            out.append(f"    goto <{p}_end>;")
            out.append(f"<{p}_go>")
            out.append("    i = 0;")
            out.append(f"<{p}_l>")
            out.append(f"    if (i == n1) goto <{p}_done>;")
            out.append(f"    if (i >= n2) goto <{p}_pad>;")
            out.append(f"    b = *:1 ({a2} + i);")
            out.append(f"    goto <{p}_st>;")
            out.append(f"<{p}_pad>")
            out.append("    b = pad;")
            out.append(f"<{p}_st>")
            out.append(f"    *:1 ({a1} + i) = b;")
            out.append("    i = i + 1;")
            out.append(f"    goto <{p}_l>;")
            out.append(f"<{p}_done>")
            out.append(f"    {a1} = {a1} + n1;")
            out.append(f"    {l1} = {l1} - n1;")
            out.append(f"    if (n1 >= n2) goto <{p}_u2>;")
            out.append(f"    {a2} = {a2} + n1;")
            out.append(f"    {l2} = {l2} - n1;")
            out.append(f"    goto <{p}_end>;")
            out.append(f"<{p}_u2>")
            out.append(f"    {a2} = {a2} + n2;")
            out.append(f"    {l2} = {l2} - n2;")
            out.append(f"<{p}_end>")
            out.append("}")
            out.append("")
            n += 1
    return "\n".join(out), n


def gen_clcl():
    """CLCL (0F), unrolled by even (R1,R2): 64 real-pcode constructors.

    PoP 7-173: R1/R2 must be even (else specification exception; odd values
    have no constructor). Addresses in R1/R2; low 24 bits of R1+1/R2+1 are
    lengths; bits 32-39 of R2+1 are the pad byte. Compared left to right;
    the shorter operand is extended on the right with the pad byte. CC:
    0 = equal, 1 = first low, 2 = first high. On inequality the addresses
    identify the unequal bytes and the lengths are reduced by the equal
    bytes compared; if the inequality is against padding, the shorter length
    becomes zero. On equality both lengths become zero and the addresses
    advance by the original lengths. Interruptibility is approximated as
    run-to-completion.
    Display prints the constrained registers as literal r-names (like STMY).
    """
    out = []
    out.append("# ===========================================================================")
    out.append("# RR: CLCL (0F), unrolled by even (R1,R2). PoP 7-173. See gen_clcl().")
    out.append("# ===========================================================================")
    out.append("")
    n = 0
    for r1 in (0, 2, 4, 6, 8, 10, 12, 14):
        for r2 in (0, 2, 4, 6, 8, 10, 12, 14):
            p = f"clcl_{r1}_{r2}"
            a1, l1, a2, l2 = f"r{r1}", f"r{r1+1}", f"r{r2}", f"r{r2+1}"
            isc = f"RR_OP=0x0F & RR_R1={r1} & RR_R2={r2}"
            disp = f'"CLCL r{r1},r{r2}"'
            out.append(f":CLCL_{r1}_{r2} {disp} is {isc}")
            out.append("{")
            out.append("    local n1:8; local n2:8; local pad:1; local pt:8;")
            out.append("    local i:8; local b1:1; local b2:1;")
            out.append(f"    n1 = {l1} & 0xffffff;")
            out.append(f"    n2 = {l2} & 0xffffff;")
            out.append(f"    pt = ({l2} >> 24) & 0xff;")
            out.append("    pad = pt[0,8];")
            out.append("    i = 0;")
            out.append(f"<{p}_l>")
            out.append(f"    if (i == n1) goto <{p}_n1d>;")
            out.append(f"    if (i == n2) goto <{p}_n2d>;")
            out.append(f"    b1 = *:1 ({a1} + i);")
            out.append(f"    b2 = *:1 ({a2} + i);")
            out.append(f"    if (b1 == b2) goto <{p}_eq>;")
            out.append(f"    if (b1 >= b2) goto <{p}_hi>;")
            out.append("    cc = 1;")
            out.append(f"    goto <{p}_upd>;")
            out.append(f"<{p}_hi>")
            out.append("    cc = 2;")
            out.append(f"    goto <{p}_upd>;")
            out.append(f"<{p}_eq>")
            out.append("    i = i + 1;")
            out.append(f"    goto <{p}_l>;")
            # op1 exhausted
            out.append(f"<{p}_n1d>")
            out.append(f"    if (n1 == n2) goto <{p}_equal>;")
            out.append(f"<{p}_p1>")
            out.append(f"    if (i == n2) goto <{p}_equal>;")
            out.append(f"    b2 = *:1 ({a2} + i);")
            out.append(f"    if (pad == b2) goto <{p}_p1e>;")
            out.append(f"    if (pad >= b2) goto <{p}_p1h>;")
            out.append("    cc = 1;")
            out.append(f"    goto <{p}_upd1>;")
            out.append(f"<{p}_p1h>")
            out.append("    cc = 2;")
            out.append(f"    goto <{p}_upd1>;")
            out.append(f"<{p}_p1e>")
            out.append("    i = i + 1;")
            out.append(f"    goto <{p}_p1>;")
            # op2 exhausted (op1 longer)
            out.append(f"<{p}_n2d>")
            out.append(f"<{p}_p2>")
            out.append(f"    if (i == n1) goto <{p}_equal>;")
            out.append(f"    b1 = *:1 ({a1} + i);")
            out.append(f"    if (b1 == pad) goto <{p}_p2e>;")
            out.append(f"    if (b1 >= pad) goto <{p}_p2h>;")
            out.append("    cc = 1;")
            out.append(f"    goto <{p}_upd2>;")
            out.append(f"<{p}_p2h>")
            out.append("    cc = 2;")
            out.append(f"    goto <{p}_upd2>;")
            out.append(f"<{p}_p2e>")
            out.append("    i = i + 1;")
            out.append(f"    goto <{p}_p2>;")
            # equal
            out.append(f"<{p}_equal>")
            out.append("    cc = 0;")
            out.append(f"    {a1} = {a1} + n1;")
            out.append(f"    {l1} = {l1} - n1;")
            out.append(f"    {a2} = {a2} + n2;")
            out.append(f"    {l2} = {l2} - n2;")
            out.append(f"    goto <{p}_end>;")
            # unequal at i (both have bytes)
            out.append(f"<{p}_upd>")
            out.append(f"    {a1} = {a1} + i;")
            out.append(f"    {l1} = {l1} - i;")
            out.append(f"    {a2} = {a2} + i;")
            out.append(f"    {l2} = {l2} - i;")
            out.append(f"    goto <{p}_end>;")
            # unequal: pad (op1) vs op2[i]; op1 (shorter) length -> 0
            out.append(f"<{p}_upd1>")
            out.append(f"    {a1} = {a1} + n1;")
            out.append(f"    {l1} = {l1} - n1;")
            out.append(f"    {a2} = {a2} + i;")
            out.append(f"    {l2} = {l2} - i;")
            out.append(f"    goto <{p}_end>;")
            # unequal: op1[i] vs pad (op2); op2 (shorter) length -> 0
            out.append(f"<{p}_upd2>")
            out.append(f"    {a1} = {a1} + i;")
            out.append(f"    {l1} = {l1} - i;")
            out.append(f"    {a2} = {a2} + n2;")
            out.append(f"    {l2} = {l2} - n2;")
            out.append(f"<{p}_end>")
            out.append("}")
            out.append("")
            n += 1
    return "\n".join(out), n


def main():
    parts = [HEADER, CC_HELPERS, RR_SECTION, RRE_SECTION, RX_SECTION,
             RI_SECTION, RXY_SECTION, STRL_SECTION, gen_clm()]
    stmy, n_stmy = gen_stmy()
    parts.append(stmy)
    cvd, n_cvd = gen_cvd()
    parts.append(cvd)
    cvb, n_cvb = gen_cvb()
    parts.append(cvb)
    mvcl, n_mvcl = gen_mvcl()
    parts.append(mvcl)
    clcl, n_clcl = gen_clcl()
    parts.append(clcl)
    with open(OUT, "w") as f:
        f.write("\n".join(parts))
    n_clm = 32
    # Count constructors: hand-written ':' lines + generated.
    import re
    text = "\n".join(parts)
    n_hand = len(re.findall(r"^:(?!.*_\\d)", text, re.M))
    print(f"wrote {OUT}")
    print(f"  hand-written constructors : {n_hand}")
    print(f"  CLM/CLMY unrolled         : {n_clm}")
    print(f"  STMY unrolled             : {n_stmy}")
    print(f"  CVD unrolled              : {n_cvd}")
    print(f"  CVB unrolled              : {n_cvb}")
    print(f"  MVCL unrolled             : {n_mvcl}")
    print(f"  CLCL unrolled             : {n_clcl}")
    print(f"  total                     : {n_hand + n_clm + n_stmy + n_cvd + n_cvb + n_mvcl + n_clcl}")


if __name__ == "__main__":
    main()
